# zeus Common Config

############################# 访问路径、端口tomcat start #############################
server:
  port: 8888
  servlet:
    context-path: 
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
############################# 访问路径、端口tomcat end ###############################

################################ spring config start ###############################
spring:
  application:
    name: zeus
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt
  servlet:
    # 文件上传配置
    multipart:
      # 指定上传文件的临时目录
      location: /opt/upload/tmp
      # 单个文件最大值
      max-file-size: 10MB
      # 单个请求文件总计最大值
      max-request-size: 100MB

# 当前项目maven激活环境，例如：dev/test/uat/prod，对应pom.xml中profile设置值
---
spring:
  profiles:
    active: ${profileActive}

# logback.xml中有详细的日志配置
logging:
  config: classpath:config/logback.xml
  #  方便spring boot admin页面上实时查看日志
  file:
    name: logs/${spring.application.name}.log
################################ spring config end #################################


############################## zeus start ##############################
zeus:
  # 是否启用ansi控制台输出有颜色的字体
  enable-ansi: true
  # 服务器ip地址
  server-ip: 127.0.0.1
  # 是否启用验证码
  enable-verify-code: false
  # 默认新建用户登录初始化密码
  login-init-salt: zeus
  login-init-password: zeus
  login-init-head: http://${zeus.server-ip}:8888/api/resource/logo.png
  # 实现baseenum接口的枚举包
  enum-packages: cn.lcarus.common.enums
  # swagger路径
  swagger-paths: /swagger-ui.html,/docs,/doc.html,/swagger-resources/**,/webjars/**,/v2/api-docs,/csrf,/v2/api-docs-ext,/null/swagger-resources/**,/service-worker.js
  # filter配置
  filter:
    request:
      enable: true
      url-patterns: /*
      order: 1
      async: true
    xss:
      enable: true
      url-patterns: /*
      order: 2
      async: true

  # 拦截器配置
  interceptor:
    permission:
      enable: false
      include-paths: /**
    resource:
      enable: false
      include-paths: ${zeus.resource-access-patterns}
    upload:
      enable: false
      include-paths: /upload/**
    download:
      enable: false
      include-paths: /download/**
    front-jwt:
      enable: true
      include-paths: /api/**
      exclude-paths: 
        - /api/grant/v1/login
        - /api/lottery/activity/**
    front-token-to-userId:
      enable: true
      include-paths: /api/**

  # aop配置
  aop:
    # aop日志配置
    log:
      # 是否启用
      enable: true
      # 是否启用requestid
      enable-request-id: true
      # requestid生成规则: uuid/idwork
      request-id-type: idwork
      # none：不打印日志
      # order：请求和响应日志，按照执行顺序分开打印
      # line：方法执行结束时，连续分开打印请求和响应日志
      # merge：方法执行结束时，合并请求和响应日志，同时打印
      log-print-type: order
      # 请求日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
      request-log-format: true
      # 响应日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
      response-log-format: true
      # 排除的路径
      exclude-paths: /,/csrf
    # 操作日志配置
    operation-log:
      # 是否启用
      enable: true
      # 排除的路径
      exclude-paths:
    # 登录日志配置
    login-log:
      # 是否启用
      enable: true
      # 登录地址
      login-path: /login
      # 登出地址
      logout-path: /logout

  # 文件上传下载配置
  # 上传路径配置
  upload-path: /opt/upload/
  # 资源访问路径
  resource-access-path: /resource/
  # 资源访问路径匹配：/resource/**
  resource-access-patterns: ${zeus.resource-access-path}**
  # 资源访问全路径前缀：http://127.0.0.1:8888/resource/
  resource-access-url: http://${zeus.server-ip}:${server.port}${server.servlet.context-path}${zeus.resource-access-path}
  # 全局允许上传的类型
  allow-upload-file-extensions: jpg,png,docx,xlsx,pptx,pdf
  # 全局允许下载的类型
  allow-download-file-extensions: jpg,png,docx,xlsx,pptx,pdf

  ############################ cors start ############################
  # cors跨域配置，默认允许跨域
  cors:
    # 是否启用跨域，默认启用
    enable: true
    # cors过滤的路径，默认：/**
    path: /**
    # 允许访问的源
    allowed-origins: '*'
    # 允许访问的请求头
    allowed-headers: '*'
    # 是否允许发送cookie
    allow-credentials: true
    # 允许访问的请求方式
    allowed-methods: option,get,post
    # 允许响应的头
    exposed-headers: 
      - token
      - Admin-Token
    # 该响应的有效时间默认为30分钟，在有效时间内，浏览器无须为同一请求再次发起预检请求
    max-age: 1800

  ############################ cors end ##############################

  ########################## resource start ##########################
  # 静态资源访问配置
  resource-handlers: |
    /static/**=classpath:/static/
    swagger-ui.html=classpath:/meta-inf/resources/
    /webjars/**=classpath:/meta-inf/resources/webjars/
    doc.html=classpath:/meta-inf/resources/
  ########################## resource end ############################

  ######################## spring shiro start ########################
  shiro:
    # 是否启用
    enable: true
    # 权限配置
    anon:
      # 排除登录登出
      - /login,/logout
      # 排除静态资源
      - /static/**,/templates/**
      # 排除swagger
      - ${zeus.swagger-paths}
      # 排除actuator
      - /actuator/**
      - # 排除首页
      - /,/index.html
      # 排除front路径
      - /api/**
    # 多行字符串权限配置
    filter-chain-definitions: |
      /resource/**=anon
      /upload/**=anon
      /verificationCode/**=anon
      /enum=anon
      /getsysuserinfo=anon

  ######################## spring shiro end ##########################

  ############################ jwt start #############################
  jwt:
    # token请求头名称
    token-name: Admin-Token
    # jwt密钥
    secret: zeus
    # 发行人
    issuer: ${spring.application.name}
    # 观众
    audience: web
    # 默认过期时间1小时，单位：秒
    expire-second: 36000
    # 是否刷新token
    refresh-token: true
    # 刷新token的时间间隔，默认10分钟，单位：秒
    refresh-token-countdown: 600
    # redis校验jwt token是否存在,可选
    redis-check: true
    # true: 同一个账号只能是最后一次登录token有效，false：同一个账号可多次登录
    single-login: false
    # 盐值校验，如果不加自定义盐值，则使用secret校验
    salt-check: true
  ############################ jwt end ###############################

############################### zeus end ###############################


############################### mybatis-plus start #################################
mybatis-plus:
  # 启动时是否检查mybatis xml文件是否存在
  check-config-location: true
  # 支持统配符 * 或者 ; 分割
  typeenumspackage: cn.chinotan.zeus.*.enums;cn.lcarus.*.enums
  # mybatis原生配置
  configuration:
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # mapper xml映射路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml
################################ mybatis-plus end ##################################


############################### hikaricp 数据源配置 start ################################
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    cachePrepStmts: true
    prepStmtCacheSize: 300
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
############################### HikariCP 数据源配置 end ################################


############################### Redis 公共配置 start ###############################
---
spring:
  redis:
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-idle: 8
        max-wait: 10s
        min-idle: 2
      shutdown-timeout: 3s
############################### Redis 公共配置 end ##################################


#################################### Swagger start #################################
---
zeus:
  # front 登录
  login:
    front:
      token-valid-time: 43200  # 登录token失效时间，单位分钟
  swagger:
    # 是否启用
    enable: true
    base:
      # 扫描的包，多个包使用逗号隔开
      package: cn.chinotan.zeus,cn.lcarus
    contact:
      email: 398851962@qq.com
      name: xingcheng
      url: https://github.com/narutoform/zeus
    description:
    title: ${spring.application.name} API Documents
    url: https://github.com/narutoform/zeus
    version: ${project.version}
    # 自定义参数配置，可配置N个
    parameter-config:
      - name: ${zeus.jwt.token-name}
        description: Token Request Header
        # header, cookie, body, query
        type: header
        data-type: String
        required: false
        # 测试接口时，自动填充token的值
        default-value:

# knife4j配置
knife4j:
  enable: ${zeus.swagger.enable}
  basic:
    enable: true
    username: zeus
    password: zeus

#################################### Swagger end ###################################


############################## Spring boot admin start ##############################
---
spring:
  boot:
    admin:
      client:
        # Spring Boot Admin服务地址，参照admin模块application.yml配置
        url: http://${zeus.server-ip}:8000
        # Spring Boot Admin账号
        username: zeus
        # Spring Boot Admin密码
        password: zeus
        # 当前项目实例名称
        instance:
          # client名称
          name: ${spring.application.name}
          # client ip端口
          service-base-url: http://${zeus.server-ip}:${server.port}
      monitor:
        period: 100000
        status-lifetime: 100000
        connect-timeout: 100000
        read-timeout: 100000

# 开启和暴露端点
management:
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      #可在线查看日志
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

# 自定义项目信息，Spring Boot Admin展示使用
info:
  project-groupId: '@project.parent.groupId@'
  project-name: ${spring.application.name}
  project-finalName: '@boot.artifact.name@'
  project-author: xingcheng
  project-description: ${spring.application.name} project
  project-sourceEncoding: '@project.build.sourceEncoding@'
  project-spring-boot-version: '@spring-boot.version@'
  project-mybatis-plus-version: '@mybatis-plus-boot-starter.version@'
  project-version: '@project.version@'
  project-website: 'https://my.oschina.net/u/3266761'
  project-home: http://${zeus.server-ip}:${server.port}${server.servlet.context-path}
  project-swagger: http://${zeus.server-ip}:${server.port}${server.servlet.context-path}/swagger-ui.html
  project-knife4j: http://${zeus.server-ip}:${server.port}${server.servlet.context-path}/doc.html
############################## Spring boot admin end ###############################


################################ sys config start ################################
scheduled:
  delay:
    enable: true
aliyun:
  oss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 
    root-url: 
lcarus:
  lottery:
    join:
      robot:
        enable: true
        robot-max-num: 51 # 最大的参与数
        robot-min-num: 30 # 最小的参与数
        robot-max-minute: 6 # 最大的参与分钟数
        robot-min-minute: 1 # 最小的参与分钟数
  wx:
    miniapp:
      subscribe-message-page: /pages/lottery/lottery
      index-page: /pages/index/index
      enable-check-signature: true # 是否校验签名
      notice:
        mini-program-state: trial # 小程序订阅消息跳转小程序类型-developer为开发版；trial为体验版；formal为正式版；默认为正式版
    ad:
      video:
        share-adUnit-id: 
        join-lottery-adUnit-id: 
guess:
  config:
    enable: true # 是否开启config
  user:
    login:
      enable-redis-check: true # 是否开启redis校验
################################ sys config end #################################
